version: "3.9"
services:
  scrapper:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: arm64v8/mysql:8 # mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'